version: '3.4'

services:
  adminer:
    container_name: adminer_goshop
    image: adminer:latest
    ports:
      - 8083:8080
    restart: unless-stopped
    networks:
      - goshoplocal
    depends_on:
      - db

  db:
    container_name: mysql_goshop
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - goshoplocal
    ports:
      - 3302:3306

  redis:
    container_name: redis_goshop
    image: redis:7-alpine
    restart: always
    volumes:
      - redisdata:/data
    networks:
      - goshoplocal
    ports:
      - 6377:6379
volumes:
  dbdata:
  redisdata:


networks:
  goshoplocal:
    name: goshoplocal
